# Header
menu:
  主页: /
  归档: /archives
  book: /book
rss: /atom.xml

# Content
excerpt_link: 全文阅读 »
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
archive_style: timelline
show_count: false

# Miscellaneous
cnzz_analytics: true
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
